pipeline {
	 agent any

	 environment {
	 	     VENV_DIR = 'venv'
	 }

	 stages {
	 	stage('Checkout') {
				  steps {
				  	git credentialsId: '', url: '', git branch: 'main'
				  }
		}

		stage('Install Dependencies') {
			       steps {
			       	     sh 'python3 -m venv $VENV_DIR'
				     sh './$VENV_DIR/bin/pip install --upgrade pip'
				     sh './$VENV_DIR/bin/pip install -r messaging_app/requirements.txt'
			       }
		}

		stage('Run Tests') {
			  steps {
			  	sh './$VENV_DIR/bin/pytest messaging_app --junitxml=report.xml'
				sh './$VENV_DIR/bin/python messaging_app/manage.py test'
			  }
		}

		stage('Publish Report') {
			  steps {
			  	junit 'report.xml'
			  }
		}
	 }

	 post {
	      always {
	      	     echo '--> Pipeline Completed'
	      }
	 }
}
