apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: green  # Switch between green or blue here
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
